export const CourseList = [
  {
    id: 1,
    subject: "Operating Systems",
    instructor: "T.M.Ha",
    credit: 4,
    size: 100,
    rest: 90,
    day: "Monday",
    startSlot: 7,
    sumSlot: 5,
    room: "A2.205",
  },
  {
    id: 2,
    subject: "Physics 4",
    instructor: "D.X.Hoi",
    credit: 2,
    size: 100,
    rest: 90,
    day: "Wednesday",
    startSlot: 1,
    sumSlot: 2,
    room: "A1.208",
  },
  {
    id: 3,
    subject: "Computer Network",
    instructor: "V.T.L.Phuong",
    credit: 4,
    size: 100,
    rest: 90,
    day: "Monday",
    startSlot: 1,
    sumSlot: 4,
    room: "A2.205",
  },
  {
    id: 4,
    subject: "Calculus 3",
    instructor: "N.N.Hai",
    credit: 4,
    size: 100,
    rest: 50,
    day: "Monday",
    startSlot: 7,
    sumSlot: 5,
    room: "A2.205",
  },
  {
    id: 5,
    subject: "Theoretical Models in Computing",
    instructor: "H.V.U.Synh",
    credit: 4,
    size: 100,
    rest: 10,
    day: "Monday",
    startSlot: 7,
    sumSlot: 5,
    room: "A2.205",
  },
  {
    id: 6,
    subject: "Critical Thinking",
    instructor: "T.T.Khoi",
    credit: 3,
    size: 100,
    rest: 10,
    day: "Monday",
    startSlot: 7,
    sumSlot: 5,
    room: "A2.205",
  },
  {
    id: 7,
    subject: "Digital Logic Design",
    instructor: "H.K.Tu",
    credit: 3,
    size: 100,
    rest: 10,
    day: "Monday",
    startSlot: 7,
    sumSlot: 5,
    room: "A2.205",
  },
  {
    id: 8,
    subject: " Object-Oriented Programming",
    instructor: "T.T.Tung",
    credit: 4,
    size: 100,
    rest: 0,
    day: "Monday",
    startSlot: 7,
    sumSlot: 5,
    room: "A2.205",
  },
];

export const RegistedCourses = [];

export const TimetableData = {
  Monday: [
    {
      id: 7,
      subject: "Digital Logic Design",
      instructor: "H.K.Tu",
      credit: 3,
      size: 100,
      rest: 10,
      day: "Monday",
      startSlot: 1,
      sumSlot: 3,
      room: "A2.205",
    },
    {
      id: 8,
      subject: " Object-Oriented Programming",
      instructor: "T.T.Tung",
      credit: 4,
      size: 100,
      rest: 10,
      day: "Monday",
      startSlot: 7,
      sumSlot: 4,
      room: "A2.205",
    },
  ],
  Tuesday: [
    {
      id: 5,
      subject: "Theoretical Models in Computing",
      instructor: "H.V.U.Synh",
      credit: 4,
      size: 100,
      rest: 10,
      day: "Tuesday",
      startSlot: 1,
      sumSlot: 4,
      room: "A2.205",
    },
    {
      id: 6,
      subject: "Critical Thinking",
      instructor: "T.T.Khoi",
      credit: 3,
      size: 100,
      rest: 10,
      day: "Tuesday",
      startSlot: 7,
      sumSlot: 3,
      room: "A2.205",
    },
  ],
  Friday: [
    {
      id: 5,
      subject: "Theoretical Models in Computing",
      instructor: "H.V.U.Synh",
      credit: 4,
      size: 100,
      rest: 10,
      day: "Tuesday",
      startSlot: 1,
      sumSlot: 4,
      room: "A2.205",
    },
    {
      id: 6,
      subject: "Critical Thinking",
      instructor: "T.T.Khoi",
      credit: 3,
      size: 100,
      rest: 10,
      day: "Tuesday",
      startSlot: 7,
      sumSlot: 3,
      room: "A2.205",
    },
  ],
};
